# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ocms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='property_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ocms.Property'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='room_name',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='property_name', chained_model_field='property_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='ocms.Property_Desc'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_desc',
            field=models.CharField(default='code', max_length=1500),
        ),
    ]
