# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocms', '0004_remove_complaint_complaint_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='dept_name',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
